application:
  name: simple-example
  project: first-demo
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: simple-example
    paths:
    - /*
